name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Releases
        path: |
          app/build/outputs/apk/release/app-release-unsigned.apk
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/outputs/apk/release/app-release-unsigned.apk"
        tag: v${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}  
